server:
  port: 8089

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 动态线程池管理配置
dynamic:
  thread:
    pool:
      config:
        redis:
          enabled: true
          host: 127.0.0.1
          port: 16379

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml